
target("CommonLib")
    add_configfiles("BuildInfo.h.in")
    devbuild_shared()
    set_group("common")
    add_includedirs(".", "../", "../../build", {public = true})
    add_headerfiles("**.h")
    add_files("**.cpp")
    add_deps("TiltedCore")
    add_packages("hopscotch-map")
